server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://mariadb.chegyyioe8xx.ap-northeast-2.rds.amazonaws.com:3306/shopping_mall
    username: admin
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true

logging:
  config: classpath:logback-spring-dev.xml

cloud:
  aws:
    credentials:
      access-key: AKIAZI2LFHYXL6MRUXVR
      secret-key: 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
    s3:
      bucketName: 2-backend-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

