server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://mariadb.chegyyioe8xx.ap-northeast-2.rds.amazonaws.com:3306/server_db
    username: admin
    password: ${{ secrets.MARIADB_PASSWORD }}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true

logging:
  config: classpath:logback-spring-dev.xml

cloud:
  aws:
    credentials:
      access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    s3:
      bucketName: ${{ secrets.AWS_S3_BUCKET_NAME }}
    region:
      static: ${{ secrets.AWS_DEFAULT_REGION }}
    stack:
      auto: false

